version: '2.0'
services:
  db:
    image: mysql
    container_name: products_db
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
      MYSQL_DATABASE: "shopify"
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d/:ro
    expose:
      - 3306
  web:
    image: products_image:latest
    container_name: products-web
    depends_on:
      - db
    ports:
     - 8888:8081
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_MYSQL_USER: "mysql"
      DB_MYSQL_PASS: "mysql"
      STAGE: "prod"
      DB_ON_CREATE_DB: "shopify"

